{% set name = "knack" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b1ac92669641b902e1aef97138666a21b8852f65d83cbde03eb9ddebf82ce121

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - argcomplete
    - colorama
    - jmespath
    - pygments
    - pyyaml
    - six
    - tabulate

test:
  imports:
    - knack
    - knack.testsdk
  requires:
    - mock
    - vcrpy

about:
  home: https://github.com/microsoft/knack
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Command-Line Interface framework

  doc_url: https://github.com/Microsoft/knack/tree/master/docs
  dev_url: https://github.com/microsoft/knack

extra:
  recipe-maintainers:
    - andreyz4k
