{% set name = "knack" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 16aa47240add6badd933a0b27576f3c090d7469177dc941e3ece05ca88123199

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - argcomplete
    - colorama
    - jmespath
    - pygments
    - pyyaml
    - six
    - tabulate

test:
  imports:
    - knack
    - knack.testsdk
  requires:
    - mock
    - vcrpy

about:
  home: https://github.com/microsoft/knack
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Command-Line Interface framework

  doc_url: https://github.com/Microsoft/knack/tree/master/docs
  dev_url: https://github.com/microsoft/knack

extra:
  recipe-maintainers:
    - andreyz4k
